name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        with:
          create_annotated_tag: true
          uses: mathieudutour/github-tag-action@master
          github_token: ${{ secrets.GITHUB_TOKEN }}
